## 6. Numpy

In [2]:
# numpy 불러와서 사용해보기
import numpy as np
np.array([1, 5, 7, 6])

array([1, 5, 7, 6])

In [3]:
np.array([1.25, 1, 5, 7])

array([1.25, 1.  , 5.  , 7.  ])

In [3]:
# numpy의 유용한 함수(방법)들
np.zeros(5, dtype=int)

array([0, 0, 0, 0, 0])

In [4]:
np.ones([2,3], dtype=float)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [5]:
np.arange(0, 10, 2)   # 0 포함 O, 10 포함 X

array([0, 2, 4, 6, 8])

In [6]:
np.linspace(0, 1, 5)  # 0 포함 O, 10 포함 O

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [7]:
np.random.seed(12)

In [7]:
np.random.random((3,3))        # 3 by 3 U(0,1) 생성

array([[0.82699609, 0.61126741, 0.44804988],
       [0.87128108, 0.24955355, 0.71770974],
       [0.01004518, 0.48362639, 0.57549793]])

In [8]:
np.random.normal(0, 1, (3,3))  # 3 by 3 N(0,1) 생성

array([[ 1.53889681, -1.17227057, -0.60326106],
       [-0.40202104,  0.88733595,  0.40523836],
       [ 1.25259229, -0.89887268, -0.49797971]])

In [9]:
np.random.randint(0, 10, (3,3)) # 3 by 3 정수(0-9) 생성

array([[6, 3, 0],
       [1, 4, 4],
       [9, 2, 4]])

In [11]:
rg = np.random.RandomState(40)  # np.random.RandomState 클래스를 rg로 객체화
rg.normal(0, 1, (3,3))

array([[-0.6075477 , -0.12613641, -0.68460636],
       [ 0.92871475, -1.84440103, -0.46700242],
       [ 2.29249034,  0.48881005,  0.71026699]])

In [10]:
# array의 객체화
import numpy as np
np.random.seed(1)
x = np.random.randint(10, size=(2,3,4))
print(x);print(x.ndim);print(x.shape);print(x.size)

[[[5 8 9 5]
  [0 0 1 7]
  [6 9 2 4]]

 [[5 2 4 2]
  [4 7 7 9]
  [1 7 0 6]]]
3
(2, 3, 4)
24


In [13]:
# array 접근과 편집(slicing)
x = np.array([0,3,5,2,4,6])  # 1차원
x[1]

3

In [14]:
x1=x[:,np.newaxis]
x1
x2=x.reshape(6,1)
x2
x3=np.reshape(x,(6,1))
x3
x4=x3.flatten()
x4

array([0, 3, 5, 2, 4, 6])

In [15]:
x[1:3]   

array([3, 5])

In [16]:
x[1:-2]

array([3, 5, 2])

In [17]:
x[::2]    # x[start:stop:step], x[start:stop:step,start:stop:step]

array([0, 5, 4])

In [18]:
x[:2]

array([0, 3])

In [19]:
x[::-1]   # 역순으로

array([6, 4, 2, 5, 3, 0])

In [20]:
x[5::-2]

array([6, 2, 3])

In [21]:
x = np.array([[1,2,3], [4,5,6], [7,8,9]])
x[:2, :2]

array([[1, 2],
       [4, 5]])

In [22]:
x[:, 0]   # 첫째 열

array([1, 4, 7])

In [23]:
x[0, :]   # 첫째 행

array([1, 2, 3])

In [24]:
x[0]

array([1, 2, 3])

In [21]:
x[1, 2]   # list에서는 x[1][2]로 같은 동작을 수행하였음

6

In [25]:
x[0, 0] = 99
x

array([[99,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [27]:
x1 = x[:2, :2]
x1

array([[99,  2],
       [ 4,  5]])

In [28]:
x1[0, 1] = 99
x1

array([[99, 99],
       [ 4,  5]])

In [25]:
print(x)  # x1을 수정하면 x에도 반영이 됨. ∵뷰 형태로 x와 동일한 객체를 참조

[[99 99  3]
 [ 4  5  6]
 [ 7  8  9]]


In [ ]:
print(id(x));print(id(x1))    # 주소는 x와 다름

In [29]:
x1_copy = x[:2, :2].copy()
x1_copy[0, 0] = 1000  # x에 영향을 주지 않음
print(x)

[[99 99  3]
 [ 4  5  6]
 [ 7  8  9]]


In [ ]:
### 6.1 numpy의 차원 변경, 분할, 덧붙이기 ###

In [30]:
# 차원 변경
import numpy as np
x = np.array([1, 2, 3])
print(x)
x.reshape((1, 3))  # 2차원 행벡터화([]가 한 겹 더 생겼음)
print(x[np.newaxis, :])
x.reshape((3, 1))  # 2차원 열벡터화
print(x[:, np.newaxis])

[1 2 3]
[[1 2 3]]
[[1]
 [2]
 [3]]


In [6]:
x = np.random.randint(10, size=(3,3,4))
print(x)
print('---------------------------')
x1 = x.reshape((3, 12))  # 3 by 4 행렬의 각 행을 옆으로 붙임
print(x1)
x2=x.reshape((-1,12))
print(np.shape(x2))
x.shape[1]

[[[3 4 3 1]
  [7 8 4 7]
  [6 8 4 1]]

 [[9 2 8 4]
  [9 5 2 3]
  [7 8 2 7]]

 [[0 6 5 5]
  [1 9 6 5]
  [2 9 5 1]]]
---------------------------
[[3 4 3 1 7 8 4 7 6 8 4 1]
 [9 2 8 4 9 5 2 3 7 8 2 7]
 [0 6 5 5 1 9 6 5 2 9 5 1]]
(3, 12)


3

In [4]:
# 분할
x = [1, 2, 3, 4, 5, 6, 7, 8]
x1, x2, x3 = np.split(x, [2,6])
print(x1, x2, x3)
x1[0] = 100  # 분할된 변수의 변경은 x에 반영되지 않음
print(x1)

[1 2] [3 4 5 6] [7 8]
[100   2]


In [29]:
x = np.random.random((4, 4));print(x)

[[0.80074457 0.96826158 0.31342418 0.69232262]
 [0.87638915 0.89460666 0.08504421 0.03905478]
 [0.16983042 0.8781425  0.09834683 0.42110763]
 [0.95788953 0.53316528 0.69187711 0.31551563]]


In [30]:
x1, x2 = np.vsplit(x, [2])  # 세로를 분할
print(x1)
print('--------------------------------------------------')
print(x2)

[[0.80074457 0.96826158 0.31342418 0.69232262]
 [0.87638915 0.89460666 0.08504421 0.03905478]]
--------------------------------------------------
[[0.16983042 0.8781425  0.09834683 0.42110763]
 [0.95788953 0.53316528 0.69187711 0.31551563]]


In [31]:
y1, y2 = np.hsplit(x, [2])  # 가로를 분할
print(y1)
print('---------------------------')
print(y2)

[[0.80074457 0.96826158]
 [0.87638915 0.89460666]
 [0.16983042 0.8781425 ]
 [0.95788953 0.53316528]]
---------------------------
[[0.31342418 0.69232262]
 [0.08504421 0.03905478]
 [0.09834683 0.42110763]
 [0.69187711 0.31551563]]


In [32]:
# 덧붙이기
x = np.array([1, 2])
y = np.array([2, 3])
z = np.array([4, 5])
np.concatenate([x, y, z])

array([1, 2, 2, 3, 4, 5])

In [33]:
xx = np.array([[1,2,3], [4,5,6]])
yy = np.array([[2,4,6], [8,7,6]])
print(np.concatenate([xx, yy]))          # 아래로 붙임
print('---------------------------')
print(np.concatenate([xx, yy], axis=1))  # 옆으로 붙임

[[1 2 3]
 [4 5 6]
 [2 4 6]
 [8 7 6]]
---------------------------
[[1 2 3 2 4 6]
 [4 5 6 8 7 6]]


In [9]:
zz = np.array([55, 66, 77])
np.vstack([zz, xx])  # 세로로 쌓기. np.concatenate([zz.reshape((1,3)), xx])과 결과 동일

array([[55, 66, 77],
       [ 1,  2,  3],
       [ 4,  5,  6]])

In [34]:
ww = np.array([[100], [200]])  # 열벡터
np.hstack([ww, xx])  # 가로로 쌓기

array([[100,   1,   2,   3],
       [200,   4,   5,   6]])

In [ ]:
### 6.2 numpy 연산 ###

In [35]:
x = np.array([1, 2, 3, 4])
print(x+3)
print(x-3)
print(x*3)
print(x/3)
print(x**3)
print(-(0.5*x+1)**2)

[4 5 6 7]
[-2 -1  0  1]
[ 3  6  9 12]
[0.33333333 0.66666667 1.         1.33333333]
[ 1  8 27 64]
[-2.25 -4.   -6.25 -9.  ]


In [36]:
print(np.exp(x))
print(np.power(3, x))
print(np.log(x))
print(np.log2(x))
print(np.log10(x))

[ 2.71828183  7.3890561  20.08553692 54.59815003]
[ 3  9 27 81]
[0.         0.69314718 1.09861229 1.38629436]
[0.        1.        1.5849625 2.       ]
[0.         0.30103    0.47712125 0.60205999]


In [37]:
M = np.ones((3, 3))
print(M)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [38]:
M1 = M + 1
print(M1)

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [14]:
a = np.array([1, 2, 3])
M2 = M + a  # row by row로 연산 수행
print(M2)

[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]


In [40]:
a = np.arange(3)
b = np.arange(3)[:, np.newaxis]
print(a);print(b)
print('---------------------------')
print(a+b)

[0 1 2]
[[0]
 [1]
 [2]]
---------------------------
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [41]:
# 기초통계량 계산
np.random.seed(13)
x = np.random.randint(10, size=(3,4))
print(x)

[[2 0 0 6]
 [2 4 9 3]
 [4 2 6 5]]


In [42]:
print(np.sum(x))           # 원소의 총 합계
print(np.min(x, axis=1))   # 각 행의 최소값
print(np.mean(x, axis=0))  # 각 열의 평균
print(np.std(x, axis=0))   # 각 열의 표준편차

43
[0 2 2]
[2.66666667 2.         5.         4.66666667]
[0.94280904 1.63299316 3.74165739 1.24721913]


In [43]:
x_std = (x - np.mean(x, axis=0))/np.std(x, axis=0)
print(np.sum(x_std, axis=0))

[ 4.44089210e-16  0.00000000e+00  1.11022302e-16 -7.77156117e-16]


In [1]:
### 6.2 논리 인덱싱(Boolean indexing)과 순서 정렬(Sorting) ###
import numpy as np
x = np.array([[1,2,3,4], [5,6,7,8]]); print(x)

[[1 2 3 4]
 [5 6 7 8]]


In [2]:
print(x >= 5)
print(np.sum(x>=5))
print(np.sum(x>=5, axis=1))  # 각 행별로 연산

[[False False False False]
 [ True  True  True  True]]
4
[0 4]


In [3]:
print(np.any(x>100))          
print(np.all(x<7, axis=0))   # 각 열별로 연산
print(np.all(x==100))

False
[ True  True False False]
False


In [2]:
# 논리 인덱싱
x = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]])
print(x)
y = np.array([1,0,1,0])
print(y)
print(x[y==0, :])  # y=0인 행과 모든 열
print('---------------------------')
print(x[:, y==0])  # 모든 행과 y=0인 열

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[1 0 1 0]
[[ 5  6  7  8]
 [13 14 15 16]]
---------------------------
[[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]]


In [3]:
# array를 활용한 인덱싱
x = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
print(x)
ind1 = np.array([2, 3, 8])
ind2 = np.array([[2,1,3], [5,2,7]])
x1 = x[ind1]
x2 = x[ind2]
print(x1)
print('---------------------------')
print(x2)

[11 22 33 44 55 66 77 88 99]
[33 44 99]
---------------------------
[[33 22 44]
 [66 33 88]]


In [6]:
# 인덱싱에서의 브로드캐스팅
x = np.arange(12).reshape((3,4))
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [7]:
y1 = np.array([1, 2, 2])
y2 = np.array([2, 0, 1])
print(y1[:,np.newaxis])
print(y2)
print(x[y1, y2])
print('---------------------------')
print(x[y1[:,np.newaxis], y2])

[[1]
 [2]
 [2]]
[2 0 1]
[6 8 9]
---------------------------
[[ 6  4  5]
 [10  8  9]
 [10  8  9]]


In [8]:
# 순서 정렬
x = np.array([2, 4, 3, 1, 5])
print(np.sort(x))

[1 2 3 4 5]


In [27]:
ind = np.argsort(x) # sort한 것의 index
print(ind) 

[3 0 2 1 4]


In [5]:
import numpy as np
x=np.random.randint(1,10, size=(2,3,4))
x

array([[[9, 4, 6, 3],
        [4, 2, 2, 3],
        [5, 1, 5, 2]],

       [[8, 7, 6, 2],
        [3, 7, 5, 3],
        [7, 6, 6, 4]]])

In [7]:
x1=x[:,-1,:]
x1

array([[5, 1, 5, 2],
       [7, 6, 6, 4]])