목적변수가 3개의 범주, 13개의 특성변수로 이루어져 있는 와인 데이터를 이용해 실습을 진행해본다.

In [1]:
import pandas as pd
import numpy as np

In [ ]:
# 데이터 불러오기. y값은 이미 범주형으로 되어있음.
dat_wine=pd.read_csv('http://archive.ics.uci.edu/ml/machine-learning-databases/'
                     'wine/wine.data',header=None)
print(dat_wine.head())
dat_wine.columns = ['class label', 'alchohol', 'malic acid', 'ash', 
                    'alcalinity of ash', 'magnesium', 'total phenols', 
                    'flavanoids', 'nonflavanoid phenols', 
                    'proanthocyanins', 'color intensity', 'hue', 
                    'OD208', 'proline']  # Column names
print('class label:', np.unique(dat_wine['class label']))  # Class 출력
dat_wine.head()

In [4]:
# 전체 data를 training set과 test set으로 split
from sklearn.model_selection import train_test_split

X, y = dat_wine.iloc[:,1:].values, dat_wine.iloc[:,0].values
X_train, X_test, y_train,y_test = \
    train_test_split(X, y, test_size=0.3, random_state=1, stratify=y)

In [5]:
# 표준화
from sklearn.preprocessing import StandardScaler

std = StandardScaler()
X_train_std = std.fit_transform(X_train)
X_test_std = std.transform(X_test)

In [10]:
# Logistic Regression with L2 or L1 Regularization
from sklearn.linear_model import LogisticRegression

lr2_10 = LogisticRegression(penalty='l2', C=10.0)  # L2 with C(=1/λ)=10
lr2_1 = LogisticRegression(penalty='l2', C=1.0)    # L2 with C(=1/λ)=1
lr2_0_1 = LogisticRegression(penalty='l2', C=0.1)  # L2 with C(=1/λ)=0.1
lr1_10 = LogisticRegression(penalty='l1', C=10.0, solver='saga', max_iter=1000)  # L1 with C(=1/λ)=10
# lr1_10 = LogisticRegression(penalty='l1', C=10.0, solver='saga', multi_class = 'ovr')
lr1_1 = LogisticRegression(penalty='l1', C=1.0, solver='saga', max_iter=1000)    # L1 with C(=1/λ)=1
lr1_0_1 = LogisticRegression(penalty='l1', C=0.1, solver='saga', max_iter=1000)  # L1 with C(=1/λ)=0.1

In [11]:
# 규제화 방법(L2 or L1)과 규제강도(λ)를 바꿔가며 accuracy score 계산
lr2_10.fit(X_train_std, y_train)
print('Training accuracy with L2 and λ=0.1:', lr2_10.score(X_train_std, y_train))
print('Test accuracy with L2 and λ=0.1:', lr2_10.score(X_test_std, y_test))

lr2_1.fit(X_train_std, y_train)  # warning..
print('Training accuracy with L2 and λ=1:', lr2_1.score(X_train_std, y_train))
print('Test accuracy with L2 and λ=1:', lr2_1.score(X_test_std, y_test))

lr2_0_1.fit(X_train_std, y_train)
print('Training accuracy with L2 and λ=10:', lr2_0_1.score(X_train_std, y_train))
print('Test accuracy with L2 and λ=10:', lr2_0_1.score(X_test_std, y_test))

lr1_10.fit(X_train_std, y_train)
print('Training accuracy with L1 and λ=0.1:', lr1_10.score(X_train_std, y_train))
print('Test accuracy with L1 and λ=0.1:', lr1_10.score(X_test_std, y_test))

lr1_1.fit(X_train_std, y_train)
print('Training accuracy with L1 and λ=1:', lr1_1.score(X_train_std, y_train))
print('Test accuracy with L1 and λ=1:', lr1_1.score(X_test_std, y_test))

lr1_0_1.fit(X_train_std, y_train)
print('Training accuracy with L1 and λ=10:', lr1_0_1.score(X_train_std, y_train))
print('Test accuracy with L1 and λ=10:', lr1_0_1.score(X_test_std, y_test))

Training accuracy with L2 and λ=0.1: 1.0
Test accuracy with L2 and λ=0.1: 0.9814814814814815
Training accuracy with L2 and λ=1: 1.0
Test accuracy with L2 and λ=1: 0.9814814814814815
Training accuracy with L2 and λ=10: 1.0
Test accuracy with L2 and λ=10: 1.0
Training accuracy with L1 and λ=0.1: 1.0
Test accuracy with L1 and λ=0.1: 0.9814814814814815
Training accuracy with L1 and λ=1: 1.0
Test accuracy with L1 and λ=1: 0.9814814814814815
Training accuracy with L1 and λ=10: 0.9838709677419355
Test accuracy with L1 and λ=10: 1.0


In [12]:
# L2 규제의 규제강도(C=1/λ)를 바꿔가며 계수 추정치 관찰 (절댓값을 줄이면서 0과 비슷하게 하는 기법, 통계에서 p-value와 비슷함)
print(lr2_10.intercept_)
print(lr2_1.intercept_)
print(lr2_0_1.intercept_)

print(lr2_10.coef_)
print(lr2_1.coef_)
print(lr2_0_1.coef_)

[ 0.64169306  0.83074708 -1.47244014]
[ 0.29349893  0.61240686 -0.90590579]
[ 0.06966557  0.45754868 -0.52721425]
[[ 1.22688919  0.15867552  0.27580037 -1.51434132  0.0864217   0.38507292
   0.91269186 -0.26694075  0.11742498  0.18962491  0.08703449  1.04977521
   1.35741915]
 [-1.59719697 -0.43899881 -1.280461    1.22777706 -0.32952624 -0.55542036
   0.98907691  0.35680474  0.43845495 -1.20896012  1.19356707  0.10602944
  -1.73128074]
 [ 0.37030777  0.2803233   1.00466063  0.28656426  0.24310454  0.17034743
  -1.90176876 -0.08986399 -0.55587993  1.0193352  -1.28060155 -1.15580464
   0.37386159]]
[[ 0.75361285  0.06105544  0.23129826 -0.89151569  0.0254355   0.29460189
   0.56203405 -0.20767898  0.13644792  0.12854884  0.10311919  0.61947322
   0.90907528]
 [-0.98692141 -0.322874   -0.6520325   0.66648352 -0.22963356 -0.20480078
   0.4387876   0.19628231  0.24626032 -0.77714941  0.63869702  0.08773225
  -1.03332463]
 [ 0.23330855  0.26181856  0.42073425  0.22503217  0.20419806 -0.08980

In [11]:
# L2 규제의 규제강도(C=1/λ)를 바꿔가며 계수 추정치 관찰 (절댓값을 줄이면서 0으로 보내는 기법, 왜곡하는 효과가 있음)
print(lr1_10.intercept_)
print(lr1_1.intercept_)
print(lr1_0_1.intercept_)

print(lr1_10.coef_)
print(lr1_1.coef_)
print(lr1_0_1.coef_)

[-2.14035866 -2.65922403 -4.16476189]
[-1.11958913 -1.13559733 -2.22622892]
[-0.29617765 -0.08175121 -0.78575087]
[[ 2.94105456  0.28661411  1.10478325 -3.13661938  0.244986    0.
   1.89714188  0.          0.          0.          0.          1.8919487
   3.25251407]
 [-2.86050792 -1.01088098 -2.63913443  1.99728475  0.         -0.94773025
   1.78186294  0.72894868  1.12998626 -3.44013092  2.28398555  0.
  -5.19649767]
 [ 0.90803487  0.20038068  1.91121041  0.          0.20378065  0.18872926
  -5.50689492 -0.9494814  -0.02848173  2.70832306 -1.49302574 -0.84299314
   0.        ]]
[[ 1.41320331  0.          0.27838963 -1.36300459  0.          0.
   1.27114553  0.          0.          0.          0.          0.7122173
   2.22002694]
 [-1.68928458 -0.37315879 -0.8247154   0.68070422 -0.11987273  0.
   0.3959537   0.01144807  0.24951005 -1.42631508  1.05996578  0.
  -2.23082137]
 [ 0.          0.23194873  0.50743267  0.          0.16131275  0.
  -2.48984944 -0.11935498  0.          1.65069

In [14]:
import warnings
warnings.filterwarnings('ignore')

lr2_10.fit(X_train, y_train)
print('Training accuracy with L2 and λ=0.1:', lr2_10.score(X_train, y_train))
print('Test accuracy with L2 and λ=0.1:', lr2_10.score(X_test, y_test))

lr2_1.fit(X_train, y_train)  # warning..
print('Training accuracy with L2 and λ=1:', lr2_1.score(X_train, y_train))
print('Test accuracy with L2 and λ=1:', lr2_1.score(X_test, y_test))

lr2_0_1.fit(X_train, y_train)
print('Training accuracy with L2 and λ=10:', lr2_0_1.score(X_train, y_train))
print('Test accuracy with L2 and λ=10:', lr2_0_1.score(X_test, y_test))

lr1_10.fit(X_train, y_train)
print('Training accuracy with L1 and λ=0.1:', lr1_10.score(X_train, y_train))
print('Test accuracy with L1 and λ=0.1:', lr1_10.score(X_test, y_test))

lr1_1.fit(X_train, y_train)
print('Training accuracy with L1 and λ=1:', lr1_1.score(X_train, y_train))
print('Test accuracy with L1 and λ=1:', lr1_1.score(X_test, y_test))

lr1_0_1.fit(X_train, y_train)
print('Training accuracy with L1 and λ=10:', lr1_0_1.score(X_train, y_train))
print('Test accuracy with L1 and λ=10:', lr1_0_1.score(X_test, y_test))

Training accuracy with L2 and λ=0.1: 0.9838709677419355
Test accuracy with L2 and λ=0.1: 0.9074074074074074
Training accuracy with L2 and λ=1: 0.9758064516129032
Test accuracy with L2 and λ=1: 0.9259259259259259
Training accuracy with L2 and λ=10: 0.9758064516129032
Test accuracy with L2 and λ=10: 0.8888888888888888
Training accuracy with L1 and λ=0.1: 1.0
Test accuracy with L1 and λ=0.1: 0.9259259259259259
Training accuracy with L1 and λ=1: 0.9838709677419355
Test accuracy with L1 and λ=1: 0.9074074074074074
Training accuracy with L1 and λ=10: 0.9354838709677419
Test accuracy with L1 and λ=10: 0.8888888888888888


In [15]:
print(lr2_10.intercept_)
print(lr2_1.intercept_)
print(lr2_0_1.intercept_)

print(lr2_10.coef_)
print(lr2_1.coef_)
print(lr2_0_1.coef_)

[-0.09143283  0.22589921 -0.13446638]
[-0.04189651  0.0995453  -0.05764879]
[-0.02672903  0.05217164 -0.0254426 ]
[[-0.36313918  0.52343764  0.33350011 -0.43963089 -0.07174     0.73305754
   1.40092718 -0.11008586  0.51884012  0.20305759 -0.0089799   0.98267424
   0.01538663]
 [ 1.43495376 -1.58748636 -0.20014058  0.40881875 -0.02453074  0.14988068
   0.48986777  0.19833982  0.26560535 -2.20119181  0.53313307  0.57652202
  -0.01819305]
 [-1.07181458  1.06404873 -0.13335952  0.03081215  0.09627075 -0.88293822
  -1.89079495 -0.08825397 -0.78444547  1.99813422 -0.52415317 -1.55919626
   0.00280642]]
[[-1.71042952e-01  1.91615570e-01  1.28113689e-01 -3.28200308e-01
  -3.08789822e-02  3.10332211e-01  5.97752851e-01 -4.90525052e-02
   2.18953782e-01  4.72670445e-02 -3.77180989e-04  4.12548185e-01
   1.06589048e-02]
 [ 5.86790039e-01 -7.21741445e-01 -7.20058149e-02  2.61703845e-01
   6.29982864e-04  9.28642240e-02  2.69739466e-01  7.92761746e-02
   1.41176899e-01 -1.06516112e+00  2.36463903e-

In [9]:
print(lr1_10.intercept_)
print(lr1_1.intercept_)
print(lr1_0_1.intercept_)

print(lr1_10.coef_)
print(lr1_1.coef_)
print(lr1_0_1.coef_)

[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[[-1.01302850e+00  2.39608807e+00  1.71991521e-01 -1.86127869e+00
   8.34950377e-02  0.00000000e+00  7.14119679e+00  0.00000000e+00
  -2.97774639e+00 -8.18214103e-01  0.00000000e+00  0.00000000e+00
   3.49411930e-02]
 [ 1.31679390e+00 -2.73038551e+00 -3.38001837e+00  9.41289186e-01
   0.00000000e+00 -1.95012089e+00  1.91790955e+00  1.23238533e+01
   2.58858839e+00 -3.24670367e+00  4.31646082e+00 -5.15270908e-01
  -2.73681581e-02]
 [-2.78642772e-01  1.40323545e+00  0.00000000e+00  3.31841490e-02
   1.17547347e-01  0.00000000e+00 -7.98095839e+00  0.00000000e+00
   0.00000000e+00  1.24944131e+00 -2.20232349e+00 -3.76082391e+00
  -6.33896232e-04]]
[[-2.34793075e-02  8.11723037e-02  0.00000000e+00 -7.05407269e-01
  -4.59876204e-02  0.00000000e+00  1.97035783e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   1.76174386e-02]
 [ 5.87514555e-01 -1.21890126e+00  0.00000000e+00  4.28854104e-01
   2.44013384e-02  0.00000000e+0